package hibernate;
// Generated 04-may-2019 10:41:16 by Hibernate Tools 4.3.1



/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private String operador;
     private String sr;
     private String producto;
     private String transp;
     private String conductor;
     private String patenteChasis;
     private String patenteAcoplado;
     private double pesoEntrada;
     private double pesoSalida;
     private double pesoNeto;
     private String fechaEntrada;
     private String horaEntrada;
     private String fechaSalida;
     private String horaSalida;

    public Factura() {
    }
    
    public Factura(String operador, String sr, String producto, String transp, String conductor, String patenteChasis, String patenteAcoplado, double pesoEntrada,
                   String fechaEntrada, String horaEntrada){
        
    }
    public Factura(int idFactura, String operador, String sr, String producto, String transp, String conductor, String patenteChasis, String patenteAcoplado, double pesoEntrada, double pesoSalida, double pesoNeto, String fechaEntrada, String horaEntrada, String fechaSalida, String horaSalida) {
        this.idFactura = idFactura;
        this.operador = operador;
        this.sr = sr;
        this.producto = producto;
        this.transp = transp;
        this.conductor = conductor;
        this.patenteChasis = patenteChasis;
        this.patenteAcoplado = patenteAcoplado;
        this.pesoEntrada = pesoEntrada;
        this.pesoSalida = pesoSalida;
        this.pesoNeto = pesoNeto;
        this.fechaEntrada = fechaEntrada;
        this.horaEntrada = horaEntrada;
        this.fechaSalida = fechaSalida;
        this.horaSalida = horaSalida;
    }    
    public Factura(String operador, String sr, String producto, String transp, String conductor, String patenteChasis, String patenteAcoplado, double pesoEntrada, double pesoSalida, double pesoNeto, String fechaEntrada, String horaEntrada, String fechaSalida, String horaSalida) {
       
       this.operador = operador;
       this.sr = sr;
       this.producto = producto;
       this.transp = transp;
       this.conductor = conductor;
       this.patenteChasis = patenteChasis;
       this.patenteAcoplado = patenteAcoplado;
       this.pesoEntrada = pesoEntrada;
       this.pesoSalida = pesoSalida;
       this.pesoNeto = pesoNeto;
       this.fechaEntrada = fechaEntrada;
       this.horaEntrada = horaEntrada;
       this.fechaSalida = fechaSalida;
       this.horaSalida = horaSalida;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public String getOperador() {
        return this.operador;
    }
    
    public void setOperador(String operador) {
        this.operador = operador;
    }
    public String getSr() {
        return this.sr;
    }
    
    public void setSr(String sr) {
        this.sr = sr;
    }
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }
    public String getTransp() {
        return this.transp;
    }
    
    public void setTransp(String transp) {
        this.transp = transp;
    }
    public String getConductor() {
        return this.conductor;
    }
    
    public void setConductor(String conductor) {
        this.conductor = conductor;
    }
    public String getPatenteChasis() {
        return this.patenteChasis;
    }
    
    public void setPatenteChasis(String patenteChasis) {
        this.patenteChasis = patenteChasis;
    }
    public String getPatenteAcoplado() {
        return this.patenteAcoplado;
    }
    
    public void setPatenteAcoplado(String patenteAcoplado) {
        this.patenteAcoplado = patenteAcoplado;
    }
    public double getPesoEntrada() {
        return this.pesoEntrada;
    }
    
    public void setPesoEntrada(double pesoEntrada) {
        this.pesoEntrada = pesoEntrada;
    }
    public double getPesoSalida() {
        return this.pesoSalida;
    }
    
    public void setPesoSalida(double pesoSalida) {
        this.pesoSalida = pesoSalida;
    }
    public double getPesoNeto() {
        return this.pesoNeto;
    }
    
    public void setPesoNeto(double pesoNeto) {
        this.pesoNeto = pesoNeto;
    }
    public String getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(String fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public String getHoraEntrada() {
        return this.horaEntrada;
    }
    
    public void setHoraEntrada(String horaEntrada) {
        this.horaEntrada = horaEntrada;
    }
    public String getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(String fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public String getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(String horaSalida) {
        this.horaSalida = horaSalida;
    }




}


